name: Run UI Tests with Allure Report

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure command-line tool
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        sudo ln -s $PWD/allure-2.27.0/bin/allure /usr/local/bin/allure
        allure --version

    - name: Clone test-service
      run: |
        git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git ../test-service-repo

    - name: Start test-service
      run: |
        cd ../test-service-repo
        docker compose up --build -d
        timeout 180 bash -c 'until curl -f http://localhost:8080/api/_/docs/swagger/; do sleep 10; done'
        echo "test-service is ready on http://localhost:8080"
        
    - name: Check test-service logs
      run: |
        cd ../test-service-repo
        echo "--- test-service logs ---"
        docker compose logs service
        echo "--- postgres logs ---"
        docker compose logs postgres

    - name: Run UI tests
      continue-on-error: true
      run: |
        pytest -m ui --alluredir=./allure_results -n 3

    - name: Run API tests
      continue-on-error: true
      run: |
        pytest -m api --alluredir=./allure_results -n 5

    - name: Generate Allure Report
      run: |
        allure generate ./allure_results -o ./allure_report --clean

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure_report
        path: allure_report/
        retention-days: 7

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure_report